### ISSUE TITLE
Bug: Camera permission needed

### ISSUE THREAD

**Issue by scoute-dich** [msoultanidis/quillnote#116]
I installed Quillnote from F-Droid (v1.3.0). It seems, that camera permission isn't declared in the manifest.

So the app crashes always, when camera is needed.

**Comment by msoultanidis** [comment]
That's weird, it works fine on all of my phones. Is your device rooted? Also what ROM are you running?

**Comment by scoute-dich** [comment]
Yes, is rooted. I'm using latest Arrow Os, based on Android 11.
![Screenshot_20210824-224727](https://user-images.githubusercontent.com/3949944/130687696-21c8efbb-8c81-4bd7-b37f-efcd9a992f53.png)
![Screenshot_20210824-224810](https://user-images.githubusercontent.com/3949944/130687781-64eab544-55a6-44ea-81c6-de4c14116cc1.png)

**Comment by scoute-dich** [comment]
And I'm using no Gapps.

**Comment by GithubUser699** [comment]
@scoute-dich @msoultanidis 

I'm using the same version from f-droid on my lineageos (Android 11) without gapps.

It's true that the app itself has no camera permission. But it starts the stock camera app (which is lineage OS' "Snap" app on my rom) and not my other camera app ("open camera").

Since you have root you migh have deleted the stock camera app which causes quillnote to crash because it cannot open any camera service now.

**Comment by msoultanidis** [comment]
Quillnote delegates image taking to camera apps you have installed on your phone. It's possible the crash is caused by lack of such apps.

**Comment by GithubUser699** [comment]
> Quillnote delegates image taking to camera apps you have installed on your phone. It's possible the crash is caused by lack of such apps.

Yes, that's excactly what I was referring to.

About the "cannot reproduce" label you added: You could disable all camera apps with adb and it should be reproducable.

However, since that's not an issue with quillnotes itself I don't think there's anything you should/could do to solve his problem.

**Comment by scoute-dich** [comment]
Yes, that was the problem.

Perhaps a solution would be to show a toast, if camera app is not reachable.
