### ISSUE TITLE
Blocked by Google Play Protect

### ISSUE THREAD

**Issue by meadows19** [msoultanidis/quillnote#58]
I tried downloading from FDroid, but the installation failed.

I tried downloading from Aurora store, but Play Protect gives a warning.

I ignore the warning and still install, but then I get this error and can't run it.

![Screenshot_20210708-013915_Aurora Store](https://user-images.githubusercontent.com/21014471/125005296-4c2f2e80-e053-11eb-9a4b-0bdeb9287bc0.png)

I then uninstall the previous version and try to again install the new version. Still blocked by Google Play Protect.

**Comment by urizev** [comment]
The apps are packaged and signed with a certificate. The certificate can be different if you install it from Google Play, F-Droid or other source.

If you install an app from F-Droid and then you try to install a new version from Play Store you may receive an error due to different signatures.

The solution is install a new version with the same signature than the current installed app.

**Comment by msoultanidis** [comment]
What @urizev said is correct. Please update your app from only one source!

**Comment by meadows19** [comment]
Oh sorry. I'm new to android. Thank you for the information!
